### ISSUE TITLE
Node.jsでやること

### ISSUE THREAD

**Issue by wal-todays** [wal-todays/TkoolSync#1]
* [ ] 対話でユーザー設定ファイル(json)を作成する
  ```json
  {
    "username":"",
    "email":"",
    "AccessToken":"",
    "remote-repository":"https://..."
  }
  ```
* [ ] Git操作を再現する
  - [x] clone
  - [x] commit
  - [x] fetch
  - [ ] marge
  - [ ] push
  - branchなどはあとで
* [ ] 競合の回避
  - [ ] 競合がある行を検出(pullかmerge前のdiffか)
  - [ ] 競合がある行のjsonを整形（1行にまとまっているのをキー毎に改行）
  - [ ] System.jsonのversionIdは常に自分の編集を採用
  - [ ] （Map00X.jsonのeventsでの例）競合があり、idが同じで、nameが違うとき、idをずらす（この場合はjsonを整形しない。）
  - [ ] 上の例のように単にjsonを整形するだけでは対応しきれない部分を作っていく

**Comment by wal-todays** [comment]
Projectsに書き直したのでクローズ

**Comment by Nute16** [comment]
age
